server:
  port: 8081

airflux:
  aircraft:
    maintaince-time: 60

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/air_flux_db
  liquibase:
    change-log: classpath:db/db.changelog-master.xml

# Uncomment this to use mysql docker and uncomment mysql connector dependency in pom.xml
#  datasource:
#    url: jdbc:mysql://localhost:3306/air_flux_db?useSSL=false
#    username: root
#    password: root
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
#        hbm2ddl:
#          auto: update
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type: TRACE